import {setupMap} from './map.js';
import {STORAGE_KEY,escapeHTML as esc,validatePlan,eventsFor} from './core.js';
import {localDate,suggestedDay,hotelOnDate,nextTransport,buildIndex,searchIndex,parseRoute} from './lookup.js';
const data=window.TRIP_DATA,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let overrides={},dayIndex=0,filter='all',editing=null;
try{const raw=localStorage.getItem(STORAGE_KEY);if(raw)overrides=validatePlan(JSON.parse(raw),data.days);}catch{toast('저장된 일정을 읽지 못해 기본 초안을 표시합니다.');}
const mapSearch=place=>'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(place);
const external=(url,label,cls='')=>`<a class="${cls}" href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(label)}</a>`;
const shortDate=date=>date.slice(5).replace('-','/');
const transportLabel=kind=>kind==='flight'?'항공':kind==='bus'?'공항버스':'기차';
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('visible'),4000);}
function persist(){renderQuick();try{localStorage.setItem(STORAGE_KEY,JSON.stringify({version:1,overrides}));toast('이 기기에 저장했어요.');}catch{toast('기기 저장 공간을 사용할 수 없어요. 일정 내보내기로 저장해 주세요.');}}
function switchTab(id,scroll=false,params={}){if(!['quick','journey','bookings','taste'].includes(id))id='quick';document.body.dataset.view=id;$('#quick').hidden=id!=='quick';$$('.panel').forEach(p=>{p.hidden=p.id!==id;p.classList.toggle('active',p.id===id);});$$('.tabs button').forEach(b=>{b.classList.toggle('active',b.dataset.tab===id);if(b.dataset.tab===id)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});const query=new URLSearchParams(params).toString();history.replaceState(null,'','#'+id+(query?'?'+query:''));if(scroll)(id==='quick'?$('#quick') : $('.tabs')).scrollIntoView({behavior:'smooth',block:'start'});}
function routeURL(day){let r=day.route;if(day.date==='2026-11-15')r=r.slice(1,5);if(r.length<2)return mapSearch(r[0]||day.city);return 'https://www.google.com/maps/dir/?api=1&origin='+encodeURIComponent(r[0])+'&destination='+encodeURIComponent(r.at(-1))+'&waypoints='+encodeURIComponent(r.slice(1,-1).join('|'))+'&travelmode=walking';}
function renderDays(){const weekdays=['일','월','화','수','목','금','토'];$('#day-list').innerHTML=data.days.map((d,i)=>`<button class="day-button ${i===dayIndex?'active':''}" data-day="${i}" ${i===dayIndex?'aria-current="date"':''}><span class="day-number">${d.date.slice(-2)}</span><span><b>${esc(d.city)}</b><small>${weekdays[new Date(d.date+'T12:00:00Z').getUTCDay()]}요일</small></span></button>`).join('');const cities=[['부다페스트','08–10 NOV',2],['빈','10–11 NOV',3],['린츠','11–13 NOV',5],['프라하','13–16 NOV',6],['드레스덴','14 NOV · 당일',7]];$('#route-strip').innerHTML=cities.map(([city,date,i],n)=>`${n?'<span class="route-link" aria-hidden="true"></span>':''}<button class="route-city ${data.days[dayIndex].city.includes(city)?'active':''}" data-day="${i}"><strong>${city}</strong><small>${date}</small></button>`).join('');}
function renderDay(){document.dispatchEvent(new CustomEvent('trip-day-selected',{detail:data.days[dayIndex].date}));renderDays();const d=data.days[dayIndex],events=eventsFor(d,overrides);$('#day-content').innerHTML=`<div class="day-header"><div><p class="day-kicker">DAY ${String(dayIndex+1).padStart(2,'0')} / ${shortDate(d.date)} / ${esc(d.city)}</p><h3>${esc(d.title)}</h3><p>${esc(d.note)}</p></div>${external(routeURL(d),'추천 동선 지도','map-link')}</div><div class="legend"><span>이동·방문 일정</span><span>추천 · 변경 가능</span></div><div class="timeline">${events.map((e,i)=>`<article class="event ${e.kind}" style="--i:${i}"><time class="event-time">${esc(e.time)}</time><div class="event-body"><div class="event-top"><h4>${esc(e.title)}</h4>${['fixed','hotel'].includes(e.kind)?`<span class="badge">${e.kind==='hotel'?'숙박 일정':'이동·방문 일정'}</span>`:''}</div><p>${esc(e.detail)}</p><div class="event-actions">${e.place?external(mapSearch(e.place),'장소 지도'):''}${!['fixed','hotel'].includes(e.kind)?`<button data-edit="${i}">수정</button><button data-delete="${i}">삭제</button>`:''}</div></div></article>`).join('')}</div><button class="add-event" id="add-event">+ 우리만의 일정 추가</button>`;}
function renderBookings(){$('#transport-list').innerHTML=data.transport.map(t=>`<article class="transport-card"><p class="eyebrow">${shortDate(t.date)} · ${t.kind==='flight'?'FLIGHT':t.kind==='bus'?'AIRPORT BUS':'RAIL'} · ${esc(t.code)}</p><h4>${esc(t.name)}</h4><div class="transport-times">${esc(t.depart)} <span>—</span> ${esc(t.arrive)}</div><strong class="small">${esc(t.seat)}</strong><p>${esc(t.note)}</p><p>${esc(t.price)}</p></article>`).join('');$('#hotel-list').innerHTML=data.hotels.map(h=>`<article class="hotel-card"><p class="eyebrow">${esc(h.city)} / ${h.nights} NIGHTS</p><h4>${esc(h.name)}</h4><span class="stay">${shortDate(h.fromDate)} — ${shortDate(h.toDate)}</span><p>${esc(h.room)} · 성인 2명<br>${esc(h.included)}</p><p>${esc(h.address)}${h.phone?'<br>'+esc(h.phone):''}</p><p>${esc(h.note)}</p><div class="hotel-links">${external(mapSearch(h.name),'숙소 지도')}</div></article>`).join('');}
function renderTaste(){$('#recommendation-list').innerHTML=data.recommendations.filter(r=>filter==='all'||r.type===filter).map(r=>`<article class="taste-card ${r.type}"><p class="eyebrow">${esc(r.city)} · ${r.date} · ${r.type==='wine'?'WINE':'TABLE'}</p><h3>${esc(r.name)}</h3><p class="address">${esc(r.address)}</p><p>${esc(r.description)}</p><p><strong>${esc(r.budget)}</strong></p><small>${esc(r.check)}</small><div class="taste-links">${external(r.url,'공식 사이트')}${external(mapSearch(r.name+' '+r.address),'위치')}</div></article>`).join('');$('#source-links').innerHTML=[...data.sources,...data.recommendations.map(r=>({title:r.name,url:r.url}))].map(s=>external(s.url,s.title)).join('');}
function getIdeas(){const day=data.days[dayIndex];return structuredClone(overrides[day.date]??day.events.filter(e=>!['fixed','hotel'].includes(e.kind)));}
function editEvent(index=null){const d=data.days[dayIndex],e=index===null?{time:'12:00',title:'',detail:'',place:''}:eventsFor(d,overrides)[index];if(e&&['fixed','hotel'].includes(e.kind))return;editing=index===null?null:{...e};for(const k of ['time','title','detail','place'])$('#edit-form').elements[k].value=e[k];$('#edit-heading').textContent=index===null?'우리만의 일정 추가':'우리 일정 바꾸기';$('#edit-dialog').showModal();}
function download(content,name,mime='application/json'){const u=URL.createObjectURL(new Blob([content],{type:mime}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
document.addEventListener('click',e=>{const b=e.target.closest('[data-tab],[data-day],[data-filter],[data-edit],[data-delete],#add-event');if(!b)return;if(b.dataset.tab)switchTab(b.dataset.tab,true);if(b.dataset.day!==undefined){dayIndex=Number(b.dataset.day);renderDay();switchTab('journey');}if(b.dataset.filter){filter=b.dataset.filter;$$('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));renderTaste();}if(b.dataset.edit!==undefined)editEvent(Number(b.dataset.edit));if(b.id==='add-event')editEvent();if(b.dataset.delete!==undefined){const d=data.days[dayIndex],e=eventsFor(d,overrides)[Number(b.dataset.delete)];if(['fixed','hotel'].includes(e.kind))return;const ideas=getIdeas();const n=ideas.findIndex(x=>x.time===e.time&&x.title===e.title&&x.detail===e.detail);if(n>=0)ideas.splice(n,1);overrides[d.date]=ideas;persist();renderDay();}});
$('#edit-form').addEventListener('submit',e=>{e.preventDefault();const f=e.currentTarget,ideas=getIdeas(),newEvent={time:f.elements.time.value,title:f.elements.title.value.trim(),detail:f.elements.detail.value,place:f.elements.place.value,kind:editing?.kind??'idea',ref:''};if(!newEvent.title)return;const index=editing?ideas.findIndex(x=>x.time===editing.time&&x.title===editing.title&&x.detail===editing.detail):-1;if(index>=0)ideas[index]=newEvent;else ideas.push(newEvent);try{const checked=validatePlan({version:1,overrides:{[data.days[dayIndex].date]:ideas}},data.days);overrides[data.days[dayIndex].date]=checked[data.days[dayIndex].date];persist();$('#edit-dialog').close();renderDay();}catch(err){toast(err.message);}});
$('#cancel-edit').addEventListener('click',()=>$('#edit-dialog').close());
$('#export-plan').addEventListener('click',()=>download(JSON.stringify({version:1,exportedAt:new Date().toISOString(),overrides},null,2),'우리의-여행일정.json'));
$('#import-plan').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>500000)throw new Error('일정 파일이 너무 커요.');overrides=validatePlan(JSON.parse(await file.text()),data.days);persist();renderDay();}catch(err){toast(err.message);}e.target.value='';});
$('#reset-plan').addEventListener('click',()=>{if(confirm('이 기기에서 수정한 추천 일정을 지우고 기본 초안으로 돌아갈까요?')){overrides={};persist();renderDay();}});
renderDay();renderBookings();renderTaste();renderQuick();applyRoute();
window.addEventListener('hashchange',applyRoute);
if('serviceWorker' in navigator&&['http:','https:'].includes(location.protocol)){navigator.serviceWorker.register('./sw.js').then(async()=>{await navigator.serviceWorker.ready;const cache=await caches.open('public-trip-v2');if((await cache.keys()).length>=8)$('#offline-status').textContent='이 기기의 오프라인 준비 완료 · 지도는 인터넷이 필요해요.';}).catch(()=>{$('#offline-status').textContent='인터넷에 연결해서 이용해 주세요.';});}else $('#offline-status').textContent='지도와 공식 사이트는 인터넷이 필요해요.';

function quickContextDate(){return $('#quick-day')?.value || data.days[suggestedDay(data.days)].date;}
function resultRoute(r){if(r.type==='hotel'||r.type==='transport')return '#bookings';if(r.type==='taste')return '#taste';return '#journey?day='+r.date;}
function resultCard(r){return `<article class="lookup-result"><div><p class="eyebrow">${esc(({day:'하루 일정',event:'일정',transport:'이동 시간',hotel:'숙소 · 주소',taste:'식탁과 와인'})[r.type])} ${r.date?esc(shortDate(r.date)):''}</p><h3>${esc(r.title)}</h3><p>${esc(r.summary)}</p></div><div class="lookup-actions">${r.place?external(mapSearch(r.place),'지도'):''}${r.url?external(r.url,'공식 사이트'):''}${['event','day'].includes(r.type)?`<button data-open-day="${r.date}">일정 열기</button>`:''}<button data-copy-result="${esc(r.id)}">내용 복사</button><button data-copy-link="${esc(resultRoute(r))}">바로가기 복사</button></div></article>`;}
function renderQuick(){
 const select=$('#quick-day');if(!select.options.length){select.innerHTML=data.days.map(d=>`<option value="${d.date}">${shortDate(d.date)} · ${esc(d.city)}</option>`).join('');select.value=data.days[suggestedDay(data.days)].date;}
 const date=quickContextDate(),d=data.days.find(x=>x.date===date),query=$('#trip-search').value,index=buildIndex(data,overrides);
 $('#quick-context').textContent=localDate()<data.days[0].date?'여행 전 · 날짜를 골라 미리 확인해요.':localDate()>data.days.at(-1).date?'여행 완료 · 지난 일정을 다시 볼 수 있어요.':'기기 현지 날짜 기준 · 필요하면 날짜를 바꾸세요.';
 const results=searchIndex(query,index,date);$('#search-results').innerHTML=query.trim()?`<p class="lookup-count">${results.length?results.length+'개 찾았어요.':'찾은 정보가 없어요. 도시명이나 예약 종류로 다시 찾아보세요.'}</p>`+results.map(resultCard).join(''):'';
 $('#quick-cards').hidden=!!query.trim();if(query.trim())return;
 const h=hotelOnDate(data.hotels,date),t=nextTransport(data.transport,date),cards=[{id:'day:'+date,type:'day',date,title:d.city+' · 오늘의 일정',summary:eventsFor(d,overrides).map(e=>e.time+' '+e.title).join(' / '),ref:'',place:''},...(t?[index.find(r=>r.id==='transport:'+t.date+':'+t.code)]:[]),...(h?[index.find(r=>r.id==='hotel:'+h.ref)]:[])];$('#quick-cards').innerHTML=cards.filter(Boolean).map(resultCard).join('');
}
function applyRoute(){const r=parseRoute(location.hash,data);if(r.day){dayIndex=data.days.findIndex(d=>d.date===r.day);renderDay();$('#quick-day').value=r.day;renderQuick();}switchTab(r.tab,false,{...(r.day?{day:r.day}:{})});}
$('#trip-search').addEventListener('input',renderQuick);$('#quick-day').addEventListener('change',renderQuick);
$('#show-install').addEventListener('click',()=>$('#install-dialog').showModal());$('#close-install').addEventListener('click',()=>$('#install-dialog').close());
document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();switchTab('quick',true);$('#trip-search').focus();}});
document.addEventListener('click',async e=>{const b=e.target.closest('[data-query],[data-open-day],[data-copy-result],[data-copy-link]');if(!b)return;if(b.dataset.query){$('#trip-search').value=b.dataset.query;renderQuick();$('#trip-search').focus();}if(b.dataset.openDay){dayIndex=data.days.findIndex(d=>d.date===b.dataset.openDay);renderDay();switchTab('journey',true,{day:b.dataset.openDay});}if(b.dataset.copyResult||b.dataset.copyLink){const r=buildIndex(data,overrides).find(x=>x.id===b.dataset.copyResult);const text=b.dataset.copyLink?new URL(b.dataset.copyLink,location.href).href:r.title+'\n'+(r.date?r.date+'\n':'')+r.summary;try{await navigator.clipboard.writeText(text);toast('복사했어요.');}catch{toast('이 브라우저에서 복사를 지원하지 않아요. 화면의 내용을 선택해 복사해 주세요.');}}});


setupMap(data).then(()=>{if(location.hash==='#quick'||!location.hash)window.scrollTo({top:0});});
