import {escapeHTML as esc} from './core.js?v=14';
export const sightseeing = [
 {city:'부다페스트',title:'도착일 · 야경보다 먼저, 휴식',pace:'이동일',slots:[['도착 후','짐 정리와 충분한 휴식'],['저녁','가까운 식당에서 여유로운 식사'],['선택','컨디션이 좋으면 다뉴브 강변 짧은 산책']],rain:'비가 오거나 피곤하면 산책을 생략하고 쉬어요.',url:'https://www.budapestinfo.hu/'},
 {city:'부다페스트',title:'관광 1일차 · 둘이 담는 성 지구',pace:'사진 · 야경',slots:[['10:00','어부의 요새와 성 지구에서 사진'],['12:30','점심 후 부다 성 주변 산책'],['16:00','카페와 휴식'],['저녁','식사 후 다뉴브 야경 또는 유람선 한 가지']],rain:'실내 관광이나 카페로 바꾸고 유람선 운항을 확인해요.',url:'https://www.budapestinfo.hu/'},
 {city:'부다페스트',title:'추가 하루 · 느긋한 페스트',pace:'여유 · 선택',slots:[['10:00','페스트 구시가지 산책'],['12:30','점심과 현지 디저트'],['14:00','박물관 또는 온천 한 곳'],['18:00','둘만의 여유로운 저녁']],rain:'실내 박물관으로 대체해요. 온천은 취향과 이용 조건을 먼저 확인해요.',url:'https://www.budapestinfo.hu/'},
 {city:'빈',title:'이동일 · 카페에서 첫인사',pace:'기차 · 휴식',slots:[['이동','부다페스트에서 빈으로 기차 이동'],['도착 후','짐 정리 후 슈테판 광장 주변 산책'],['오후','전통 카페에서 휴식'],['저녁','가까운 식당에서 저녁']],rain:'이동이 늦어지면 광장 산책을 생략해요.',url:'https://www.wien.info/en'},
 {city:'빈',title:'관광 1일차 · 벨베데레와 음악',pace:'미술 · 정원',slots:[['10:00','벨베데레 미술관과 정원'],['12:30','점심 후 도심 산책'],['16:00','카페와 숙소 휴식'],['저녁','식사 후 예약 가능한 음악 공연 또는 야경 산책']],rain:'정원 대신 미술관을 천천히 봐요. 공연은 실제 일정과 입장 가능 여부를 확인해요.',url:'https://www.belvedere.at/en'},
 {city:'빈',title:'추가 하루 · 궁전에서 천천히',pace:'궁전 · 사진',slots:[['10:00','쇤브룬 궁전과 정원'],['12:30','점심'],['14:00','정원 산책과 사진'],['16:00','휴식 후 여유로운 저녁']],rain:'궁전 실내 입장 가능 여부를 확인하고 정원 산책은 줄여요.',url:'https://www.schoenbrunn.at/en/'},
 {city:'린츠',title:'경유일 · 작은 도시의 강변',pace:'짧은 산책',slots:[['이동','빈에서 린츠로 기차 이동'],['도착 후','짐 맡기기와 중앙광장·구시가지'],['오후','카페와 다뉴브 강변 산책'],['여유가 있다면','슐로스베르크 또는 푀스틀링베르크 전망']],rain:'실내 카페나 박물관으로 대체해요. 다음 기차가 가까우면 전망대는 생략해요.',url:'https://www.linztourismus.at/en/'},
 {city:'프라하',title:'도착일 · 구시가지의 첫 저녁',pace:'기차 · 휴식',slots:[['이동','린츠에서 프라하로 기차 이동'],['도착 후','짐 정리와 휴식'],['저녁','구시가지 광장 주변에서 식사와 짧은 산책']],rain:'비가 오거나 피곤하면 식사 후 바로 쉬어요.',url:'https://prague.eu/en/'},
 {city:'프라하',title:'관광 1일차 · 카를교와 캄파',pace:'산책 · 사진',slots:[['09:00','카를교에서 둘이 사진'],['10:00','말라스트라나와 캄파 산책'],['12:30','점심 후 카페·휴식'],['16:00','구시가지 산책과 저녁']],rain:'강변 산책을 줄이고 실내 미술관이나 카페 한 곳을 골라요.',url:'https://prague.eu/en/objevujte/charles-bridge-karluv-most/'},
 {city:'프라하',title:'추가 하루 · 성 지구와 느린 오후',pace:'성 · 정원',slots:[['10:00','프라하 성 지구'],['12:30','점심'],['14:00','정원 또는 미술관 한 곳'],['16:00','휴식 후 블타바 강변 저녁 산책']],rain:'정원 대신 입장 가능한 실내 시설을 골라요.',url:'https://prague.eu/en/objevujte/prague-castle-prazsky-hrad/'},
 {city:'드레스덴',title:'당일 왕복 · 엘베강의 한 장면',pace:'기차 · 당일치기',slots:[['출발','프라하에서 드레스덴으로 기차 이동'],['도착 후','츠빙거와 구시가지'],['점심 후','프라우엔 교회 주변과 브륄 테라스'],['귀환 전','역 이동·식사 여유를 남기고 프라하행 기차']],rain:'박물관은 한 곳만 선택해요. 실제 왕복 기차 시간에 맞춰 관광을 줄여요.',url:'https://www.dresden.de/en/tourism/tourism.php'},
 {city:'귀국',title:'공항으로 · 마지막까지 여유롭게',pace:'이동일',slots:[['출발 전','짐 정리와 식사, 공항 이동'],['이동','프라하 → 헬싱키 → 인천'],['환승','탑승구와 수속 시간을 확인하며 공항에서 휴식']],rain:'헬싱키 환승 관광은 실제 환승 여유가 확인될 때만 별도로 선택해요.',url:'https://www.finavia.fi/en/airports/helsinki-airport/airport/services-facilities/transfer'}
];
export function setupItinerary(){
 const host=document.querySelector('#itinerary');if(!host)return;
 const cities=['모두',...new Set(sightseeing.map(d=>d.city))];
 host.innerHTML=`<div class="section-head"><div><p class="eyebrow">OUR HONEYMOON, SLOWLY</p><h2>함께 걷고, 오래 기억할 하루.</h2></div></div><p class="schedule-intro">도시 이동 순서에 맞춘 신혼여행 관광 추천표예요. 실제 예약 일정이 아닌 관광 블록이며, 추가 하루는 체류 여유에 맞춰 선택해요. 표시된 시간은 현지 시간 기준의 제안입니다.</p><div class="schedule-filters" aria-label="관광 도시 선택">${cities.map((c,i)=>`<button data-city-filter="${esc(c)}" aria-pressed="${i===0}">${esc(c)}</button>`).join('')}</div><div class="schedule-grid"></div>`;
 const render=city=>{host.querySelector('.schedule-grid').innerHTML=sightseeing.filter(d=>city==='모두'||d.city===city).map(d=>`<article class="schedule-card"><p class="eyebrow">${esc(d.city)} · ${esc(d.pace)}</p><h3>${esc(d.title)}</h3><ol>${d.slots.map(([time,activity])=>`<li><time>${esc(time)}</time><span>${esc(activity)}</span></li>`).join('')}</ol><p class="schedule-rain">${esc(d.rain)}</p><div class="schedule-actions"><a href="${esc(d.url)}" target="_blank" rel="noopener noreferrer">공식 관광 안내 ↗</a>${d.city!=='귀국'?`<button data-map-city="${esc(d.city)}">도시 지도 보기</button>`:''}</div></article>`).join('');};
 host.addEventListener('click',e=>{const b=e.target.closest('button');if(b?.dataset.cityFilter){host.querySelectorAll('[data-city-filter]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));render(b.dataset.cityFilter);}if(b?.dataset.mapCity){document.dispatchEvent(new CustomEvent('trip-city-selected',{detail:b.dataset.mapCity}));document.querySelector('.map-opening')?.scrollIntoView({block:'start'});}});render('모두');
}
