import{escapeHTML as esc}from'./core.js';
const points={인천:[126.45,37.46],헬싱키:[24.97,60.32],부다페스트:[19.08,47.50],빈:[16.38,48.19],린츠:[14.29,48.29],프라하:[14.44,50.08],드레스덴:[13.73,51.04]};
const label=s=>s.replace(/\s*공항.*$/,'').trim();
let geography,paused=false;
export async function setupMap(data){const host=document.querySelector('#travel-map');if(!host)return;const segments=data.transport.filter(t=>!t.ref.startsWith('korea-')).map(t=>({...t,from:label(t.name.split('→')[0]),to:label(t.name.split('→')[1]||'')})).filter(t=>points[t.from]&&points[t.to]);
const select=document.querySelector('#map-segment');select.innerHTML=segments.map((s,i)=>`<option value="${i}">${s.date.slice(5).replace('-','/')} · ${esc(s.from)} → ${esc(s.to)} · ${s.kind==='flight'?'비행기':'기차'}</option>`).join('');
try{geography=await(await fetch('./assets/world.json')).json();}catch{geography={features:[]};}
function render(){const s=segments[Number(select.value)||0],world=s.kind==='flight',b=world?[-15,143,20,73]:[7,24,43.5,54],w=1000,h=world?400:460;const xy=([lon,lat])=>[(lon-b[0])/(b[1]-b[0])*w,(b[3]-lat)/(b[3]-b[2])*h];const land=geography.features.map(f=>{const polys=f.geometry.type==='MultiPolygon'?f.geometry.coordinates:[f.geometry.coordinates];return polys.map(poly=>poly.map(ring=>{let path='';ring.forEach((p,i)=>{const [x,y]=xy(p);path+=(i===0||Math.abs(p[0]-ring[i-1][0])>180?'M':'L')+x.toFixed(1)+','+y.toFixed(1);});return path+'Z';}).join('')).join('');}).join('');const a=xy(points[s.from]),z=xy(points[s.to]);const mx=(a[0]+z[0])/2,my=(a[1]+z[1])/2-(world?90:20);const route=`M${a.join(',')} Q${mx},${my} ${z.join(',')}`;const stations=Object.entries(points).filter(([name])=>world?['인천','헬싱키','부다페스트','프라하'].includes(name):name!=='인천'&&name!=='헬싱키');const labels=stations.map(([name,p])=>{const [x,y]=xy(p),active=name===s.from||name===s.to;return`<g class="map-station ${active?'selected':''}"><circle cx="${x}" cy="${y}" r="${active?6:3}"/><text x="${x+(name==='인천'?-12:12)}" y="${y+(name==='빈'?20:-12)}" text-anchor="${name==='인천'?'end':'start'}">${name}</text></g>`;}).join('');
host.innerHTML=`<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="${esc(s.from)}에서 ${esc(s.to)}까지 ${world?'비행기':'기차'} 이동 경로"><defs><pattern id="map-grid" width="70" height="70" patternUnits="userSpaceOnUse"><path d="M70 0H0V70" fill="none" stroke="#d4ddd4" stroke-width=".5"/></pattern></defs><rect width="${w}" height="${h}" fill="#e6ede8"/><rect width="${w}" height="${h}" fill="url(#map-grid)"/><path d="${land}" fill="#f8f7ed" stroke="#d0d7c8" stroke-width=".8"/><path id="active-route" d="${route}" class="map-route-shadow"/><path d="${route}" class="map-route ${world?'air':'rail'}"/>${labels}<g class="map-vehicle"><animateMotion dur="${world?10:7}s" repeatCount="indefinite" rotate="auto" path="${route}"/><circle r="17" fill="#1f493f"/>${world?'<path d="M11 0L-9 -9L-5 -1L-12 -3L-10 0L-12 3L-5 1L-9 9Z" fill="#fff"/>':'<rect x="-10" y="-6" width="20" height="12" rx="4" fill="#fff"/><path d="M-5 -3H6M-7 8H7" stroke="#1f493f" stroke-width="2"/>'}</g></svg>`;
document.querySelector('#map-mode').textContent=world?'KOREA → EUROPE':'CENTRAL EUROPE';document.querySelector('#map-caption').innerHTML=`<strong>${esc(s.from)} <span>→</span> ${esc(s.to)}</strong><span>${esc(s.code)} · ${esc(s.depart)} 출발 / ${esc(s.arrive)} 도착</span>`;if(paused||matchMedia('(prefers-reduced-motion: reduce)').matches)host.querySelector('svg').pauseAnimations();}
select.addEventListener('change',render);document.querySelector('#map-pause').addEventListener('click',()=>{paused=!paused;const svg=host.querySelector('svg');paused?svg.pauseAnimations():svg.unpauseAnimations();document.querySelector('#map-pause').textContent=paused?'재생':'일시정지';});document.addEventListener('trip-day-selected',e=>{const i=segments.findIndex(t=>t.date===e.detail);if(i>=0){select.value=String(i);render();}});render();}
