import test from 'node:test';import assert from 'node:assert/strict';import{readFile,readdir}from'node:fs/promises';import vm from'node:vm';import{escapeHTML,searchRecommendations,publicRoute}from'../core.js';
const read=f=>readFile(new URL('../'+f,import.meta.url),'utf8');const c={window:{}};vm.runInNewContext(await read('data.js'),c);const d=c.window.TRIP_DATA;
test('public records use a strict schema without itinerary or booking fields',()=>{
 const schemas={sources:['title','url'],recommendations:['city','name','type','address','description','budget','url','check'],transport:['name','kind','code']};
 for(const [group,keys] of Object.entries(schemas))for(const row of d[group])assert.deepEqual(Object.keys(row).sort(),keys.sort());
 assert(d.transport.some(t=>t.kind==='bus'));assert(d.transport.some(t=>t.kind==='train'));
});
test('only public guide data is present',()=>{assert.deepEqual(Object.keys(d).sort(),['recommendations','sources','transport']);assert.equal(d.recommendations.length,10);assert(d.transport.every(t=>!t.date&&!t.depart&&!t.arrive&&!t.ref&&!t.seat&&!t.price));assert(!JSON.stringify(d).match(/결혼식|청첩장|예약번호|\d+호차/));});
test('static runtime has no private UI, API or cryptographic payload',async()=>{for(const file of ['public.js','core.js','index.html','data.js','sw.js'])assert(!((await read(file)).match(/vault\.js|TRIP_VAULT|decryptVault|ciphertext|PBKDF2|AES-GCM|\/api\/|type="password"|id="(?:vault|bookings|content-dialog)"/)),file);const names=await readdir(new URL('..',import.meta.url));for(const old of ['app.js','lookup.js','vault.js','gate.js','vault-client.js','editor.js'])assert(!names.includes(old),old);});
test('public search and filters work without personal schedule',()=>{assert.equal(searchRecommendations(d.recommendations,'프라하').length,2);assert.equal(searchRecommendations(d.recommendations,'','wine').length,3);assert.equal(searchRecommendations(d.recommendations,'wine-does-not-exist').length,0);assert.equal(searchRecommendations(d.recommendations,'café').length,1);assert.equal(searchRecommendations(d.recommendations,'').length,10);});
test('old private or dated links land on public search',()=>{for(const hash of ['#vault','#bookings','#journey?day=example'])assert.equal(publicRoute(hash),'#quick');assert.equal(publicRoute('#taste'),'#taste');assert.equal(escapeHTML('<script>'), '&lt;script&gt;');});
test('public-only navigation and installed start URL',async()=>{assert(!(await read('index.html')).includes('#vault'));assert.equal(JSON.parse(await read('manifest.webmanifest')).start_url,'./');});
test('service worker clears actual legacy caches and intercepts public whitelist only',async()=>{const handlers={},deleted=[],added=[];const context={URL,Response,Set,Promise,caches:{open:async()=>({addAll:async f=>added.push(...f)}),keys:async()=>['public-trip-v4','honeymoon-old','trip-public-old','trip-public-guide-v9','unrelated'],delete:async k=>deleted.push(k)},self:{registration:{scope:'https://example.github.io/trip-public/'},addEventListener:(n,f)=>handlers[n]=f,skipWaiting:async()=>{},clients:{claim:async()=>{}}}};vm.runInNewContext(await read('sw.js'),context);let done;handlers.install({waitUntil:p=>done=p});await done;assert.equal(added.length,14);assert(added.includes('./public.js'));assert(!added.some(f=>/vault|gate|editor|api/.test(f)));handlers.activate({waitUntil:p=>done=p});await done;assert.deepEqual(deleted,['public-trip-v4','honeymoon-old','trip-public-old']);for(const path of ['vault.js','api/vault','index.html?private=1'])handlers.fetch({request:{method:'GET',url:'https://example.github.io/trip-public/'+path},respondWith:()=>assert.fail(path)});});
